# Generated by Django 2.2.5 on 2019-09-24 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('primary_number', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('current_age', models.IntegerField()),
                ('birth_city', models.CharField(max_length=100)),
                ('birth_country', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('active', models.BooleanField()),
                ('alternate_captain', models.BooleanField()),
                ('captain', models.BooleanField()),
                ('rookie', models.BooleanField()),
                ('shoots_catches', models.CharField(max_length=5)),
                ('on_current_roster', models.BooleanField()),
                ('position', models.CharField(choices=[('LW', 'Left Wing'), ('RW', 'Right Wing'), ('C', 'Centre'), ('LD', 'Left Defense'), ('RD', 'Right Defense'), ('G', 'Goalie')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=10)),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('points', models.IntegerField()),
                ('pim', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('games', models.IntegerField()),
                ('power_play_goals', models.IntegerField()),
                ('power_play_points', models.IntegerField()),
                ('shot_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('game_winning_goals', models.IntegerField()),
                ('shorthanded_goals', models.IntegerField()),
                ('shorthanded_points', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GraphQL_NHL.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GraphQL_NHL.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='aggregate_stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='GraphQL_NHL.Statline'),
        ),
        migrations.AddField(
            model_name='player',
            name='all_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='GraphQL_NHL.Statline'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GraphQL_NHL.Roster'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GraphQL_NHL.Conference')),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='divisions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='GraphQL_NHL.Division'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='GraphQL_NHL.Venue')),
                ('abbreviation', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('first_year_of_play', models.CharField(max_length=10)),
                ('official_site_url', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('all_rosters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='GraphQL_NHL.Roster')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GraphQL_NHL.Conference')),
                ('current_roster', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='GraphQL_NHL.Roster')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GraphQL_NHL.Division')),
            ],
        ),
        migrations.AddField(
            model_name='statline',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GraphQL_NHL.Team'),
        ),
        migrations.AddField(
            model_name='roster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='GraphQL_NHL.Team'),
        ),
        migrations.AddField(
            model_name='division',
            name='teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='GraphQL_NHL.Team'),
        ),
        migrations.AddField(
            model_name='conference',
            name='teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='GraphQL_NHL.Team'),
        ),
    ]
